### ISSUE TITLE
Error resolving kilt (~> 0.3.3, ~> 0.4.0) on shards update

### ISSUE THREAD

**Issue by mikeeus** [amberframework/quartz-mailer#7]
Hi, I've been getting this error when trying `shards update` on a new amber project. 

```
Updating https://github.com/amberframework/amber.git
Updating https://github.com/luislavena/radix.git
Updating https://github.com/jeromegn/kilt.git
Updating https://github.com/jeromegn/slang.git
Updating https://github.com/stefanwille/crystal-redis.git
Updating https://github.com/mosop/cli.git
Updating https://github.com/mosop/optarg.git
Updating https://github.com/mosop/callback.git
Updating https://github.com/mosop/string_inflection.git
Updating https://github.com/mosop/teeplate.git
Updating https://github.com/TechMagister/crystal-icr.git
Updating https://github.com/TechMagister/sentry.git
Updating https://github.com/juanedi/micrate.git
Updating https://github.com/crystal-lang/crystal-db.git
Updating https://github.com/jwaldrip/shell-table.cr.git
Updating https://github.com/askn/spinner.git
Updating https://github.com/will/crystal-pg.git
Updating https://github.com/crystal-lang/crystal-mysql.git
Updating https://github.com/crystal-lang/crystal-sqlite3.git
Updating https://github.com/amberframework/granite-orm.git
Updating https://github.com/amberframework/quartz-mailer.git
Error resolving kilt (~> 0.3.3, ~> 0.4.0)

```

My shard.yml file
```
name: amber
version: 0.1.0

authors:
  - Amber <amberframework.org>

crystal: 0.23.1

license: UNLICENSED

targets:
  amber:
    main: src/amber.cr

  amber:
    main: lib/amber/src/amber/cli.cr

dependencies:
  amber:
    github: amberframework/amber
    version: 0.3.0

  granite_orm:
    github: amberframework/granite-orm

  quartz_mailer:
    github: amberframework/quartz-mailer

  jasper_helpers:
    github: amberframework/jasper-helpers

  pg:
    github: will/crystal-pg

  jennifer:
    github: imdrasil/jennifer.cr

  sam:
    github: imdrasil/sam.cr

development_dependencies:
  amber_spec:
    github: amberframework/amber-spec
```

I noticed your last commit was upgrading kilt to 4.0 so it may related to that, but since this is my first Crystal app, let alone amber, I don't know how to troubleshoot it.
